<?php
    echo $this->render('flightzilla/index/partial/header.phtml');
    $this->sMemberName = $this->oResourceManager->getResourceByLogin($this->layout()->sCurrentUser);
    $this->oResource = $this->oResourceManager->getResource($this->sMemberName);
?>

<ul class="nav nav-tabs" id="ticket-tab">
    <li class="active"><a href="#tab-sprint" data-toggle="tab">Sprint</a></li>
    <li><a href="#tab-tickets" data-toggle="tab">Tickets</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane active" id="tab-sprint">
        <div class="row-fluid kanban">
            <?php
            $this->sCarousel = sprintf('member-carousel-%s', 1);
            $this->aMemberWeekTickets = (isset($this->aWeekTickets[$this->sMemberName]) === true) ? $this->aWeekTickets[$this->sMemberName] : array();
            echo $this->render('flightzilla/team/partial/sprint-carousel.phtml');
            ?>
        </div>
    </div>
    <div class="tab-pane" id="tab-tickets">
        <div class="row-fluid kanban">
            <?php
            $this->aStack = (isset($this->aTeamBugs[$this->sMemberName]) === true) ? $this->aTeamBugs[$this->sMemberName] : array();
            echo $this->render('flightzilla/index/partial/member.phtml');
            ?>
        </div>
    </div>
</div>

<div class="row-fluid">
<?php
    if ($this->iEntries > 0) {
        foreach ($this->aTasks as $this->aItems) {
            if (empty($this->aItems['stack']) !== true) {
                echo $this->render('flightzilla/index/partial/tickets-half-width.phtml');
            }
        }
    }
    else {
?>
    <div class="center chuck span4">
        <div class="alert alert-success">
            <strong>Chuck likes this!</strong> Nothing to do here.
        </div>
        <img class="chuck" src="<?php echo sprintf('%s/img/chuck/%s', $this->basePath(), \Flightzilla\Model\Chuck::OK); ?>" />
    </div>
<?php
    }
?>
</div>

<?php
echo $this->render('flightzilla/index/partial/deadline.phtml');
?>

<blockquote>
    <h3 class="table-toggle">Untouched Tickets</h3>
</blockquote>
<form style="display: none" id="buglist-form" method="get" target="_blank" action="#">
<?php
echo $this->partial('flightzilla/index/partial/table.phtml', array(
    'caption' => 'Untouched Tickets',
    'sBugzilla' => $this->layout()->sBugzilla,
    'bugs' => $this->aUntouched,
    'ready' => \Flightzilla\Model\Ticket\Type\Bug::STATUS_RESOLVED
));
?>
</form>
<h4 id="quickList" class="bugCount" style="display:none"></h4>
