<?php echo $this->render('flightzilla/index/partial/header.phtml'); ?>

<div class="row-fluid kanban">
<?php
    $this->sMemberName = $this->oResourceManager->getResourceByLogin($this->layout()->sCurrentUser);
    $this->aStack = (isset($this->aTeamBugs[$this->sMemberName]) === true) ? $this->aTeamBugs[$this->sMemberName] : array();

    echo $this->render('flightzilla/index/partial/member.phtml');
?>
</div>

<div class="row-fluid">
<?php
    if ($this->iEntries > 0) {
        foreach ($this->aTasks as $this->aItems) {
            if (empty($this->aItems['stack']) !== true) {
                echo $this->render('flightzilla/index/partial/tickets-half-width.phtml');
            }
        }
    }
    else {
?>
    <div class="center chuck span4">
        <div class="alert alert-success">
            <strong>Chuck likes this!</strong> Nothing to do here.
        </div>
        <img class="chuck" src="<?php echo sprintf('%s/img/chuck/%s', $this->basePath(), \Flightzilla\Model\Chuck::OK); ?>" />
    </div>
<?php
    }
?>
</div>

<?php
echo $this->render('flightzilla/index/partial/deadline.phtml');
?>

<blockquote>
    <h3 class="table-toggle">Untouched Tickets</h3>
</blockquote>
<form style="display: none" id="buglist-form" method="get" target="_blank" action="#">
<?php
echo $this->partial('flightzilla/index/partial/table.phtml', array(
    'caption' => 'Untouched Tickets',
    'sBugzilla' => $this->layout()->sBugzilla,
    'bugs' => $this->aUntouched,
    'ready' => \Flightzilla\Model\Ticket\Type\Bug::STATUS_REVIEWED
));
?>
</form>
<h4 id="quickList" class="bugCount" style="display:none"></h4>
