<div class="jumbotron">
    <form class="form-horizontal" method="POST" action="<?php echo $this->url('login')?>">
        <legend>Login to <b><?php echo $this->layout()->sName; ?></b></legend>
        <fieldset>
            <div class="form-group">
                <label class="control-label col-lg-2" for="username">Username</label>
                <div class="col-lg-4">
                    <input id="username" class="form-control" type="text" name="username" />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2" for="password">Password</label>
                <div class="col-lg-4">
                    <input id="password" class="form-control" type="password" name="password" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-offset-2 col-lg-4">
                    <button class="btn btn-primary btn-large">Login</button>
                </div>
            </div>
        </fieldset>
    </form>

    <a href="https://github.com/hpbuniat/flightzilla"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>
</div>
