<?php echo $this->render('flightzilla/index/partial/header.phtml')?>

<div id="content-outer">
<div id="content">

<form class="form-horizontal" method="POST" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'summary'))?>">
    <fieldset>
        <div class="control-group">
            <label class="control-label" for="username">Date</label>
            <div class="controls">
                <div class="input-append">
                    <input id="username" type="text" name="username" value="<?php echo $this->sDate;?>" />
                    <button class="btn input-append">Summary</button>
                </div>
            </div>
        </div>
    </fieldset>
</form>
<table cellpadding="5" border="1" style="width:1000px;margin-bottom:10px;">
    <?php foreach($this->bugsSummary as $tr):?>
        <?php echo $tr?>
        <?php if(stristr($tr, 'subtotal') !== false) :?>
        <tr>
            <td colspan="5">
                <textarea cols="120" rows="5"></textarea>
            </td>
        </tr>
        <?php endif;?>
    <?php endforeach?>

    <tr>
        <td colspan="5">
            Sonstige Anmerkungen:
        </td>
    </tr>
    <tr>
        <td colspan="5">
            <textarea cols="120" rows="10"></textarea>
        </td>
    </tr>
</table>

</div>
<div class="clear">&nbsp;</div>
</div>
<div class="clear">&nbsp;</div>
