<?php echo $this->render('index/partial/header.phtml')?>
<div class="row-fluid">
<?php
echo $this->partial('planning/partial/sidebar.phtml', array(
     'sHeading' => 'Projekte',
     'aStack' => $this->aStack,
));
?>
<div class="span10">
<?php foreach ($this->aErrors as $sError): ?>
    <div class="alert alert-error">
      <button class="close" data-dismiss="alert">×</button>
      <strong>Error!</strong> <?php echo $sError; ?>
    </div>
<?php endforeach; ?>
    <div class="hidden" id="ganttGraph">

    </div>

    <script type="text/javascript">
        $(function() {
            $("#ganttGraph").gantt({
                source: <?php echo $this->render('planning/data.phtml'); ?>,
                navigate: "scroll",
                scale: "weeks",
                maxScale: "months",
                minScale: "days",
                dow: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
                itemsPerPage: 50
            });
        });
    </script>

</div>
</div>