<form id="change-form" method="GET" action="<?php echo $this->url(array('ticket' => 'index', 'action' => 'modify'))?>">
    <?php
    foreach ($this->aTickets as $oTicket):
    /* @var $oTicket Model_Ticket_Type_Bug */
    ?>
    <blockquote>
    <?php
        $this->oTask = $oTicket;
        echo sprintf('<p>%s</p>', $this->render('index/partial/bug-line.phtml'));
    ?>
        <ul>

            <?php if ($oTicket->hasFlag(Model_Ticket_Type_Bug::FLAG_TESTING) === false): ?>
            <li>
                <label class="checkbox">
                    <input type="checkbox" value="setTestingRequest" name="modify[<?php echo $oTicket->id();?>][]" />
                    Check, if testing of the changes is requested
                </label>
            </li>
            <?php elseif ($oTicket->isFailed() === true and $oTicket->hasFlag(Model_Ticket_Type_Bug::FLAG_TESTING, Model_Ticket_Source_Bugzilla::BUG_FLAG_GRANTED) === false): ?>
            <li>
                <label class="checkbox">
                    <input type="checkbox" value="reTest" name="modify[<?php echo $oTicket->id();?>][]" />
                    Check, if the changes should be tested again
                </label>
            </li>
            <?php endif; ?>

            <?php if ($oTicket->isMergeable() === true): ?>
            <li>
                <label class="checkbox">
                    <input type="checkbox" value="setMerged" name="modify[<?php echo $oTicket->id();?>][]" />
                    Check, if the changes have been merged into the master-branch/trunk
                </label>
            </li>
            <?php endif;?>

            <?php if ($oTicket->hasFlag(Model_Ticket_Type_Bug::FLAG_TESTSERVER, '+') !== true): ?>
            <li>
                <label class="checkbox">
                    <input type="checkbox" value="setStaged" name="modify[<?php echo $oTicket->id();?>][]" />
                    Check, if the changes have been deployed to the test-system
                </label>
            </li>
            <?php endif;?>

            <?php if ($oTicket->hasFlag(Model_Ticket_Type_Bug::FLAG_DBCHANGE, '?') === true): ?>
            <li>
                <label class="checkbox">
                    <input type="checkbox" value="setDbChanged" name="modify[<?php echo $oTicket->id();?>][]" />
                    Check, if the Database-Changes have been deployed to production
                </label>
            </li>
            <?php endif;?>
        </ul>
    </blockquote>
    <?php
    endforeach;
    ?>
    <hr />
    <p class="pull right">
        <input type="submit" value="Change selected tickets" class="btn btn-primary btn-large" />
    </p>
</form>

