<div class="row">
    <div class="col-lg-2">
        <div class="well sidebar-nav">

            <form action="watchlist/add" method="post">
                <div class="input-append">
                    <input class="col-lg-9" id="appendedInputButton" type="text" name="ticketId" placeholder="add ticket">
                    <button class="btn submitForm" type="button">Go!</button>
                </div>
            </form>
            <form action="watchlist/remove" method="post">
                <div class="input-append">
                    <input class="col-lg-9" id="appendedInputButton" type="text" name="ticketId"
                           placeholder="remove ticket">
                    <button class="btn submitForm" type="button">Go!</button>
                </div>
            </form>

            <?php
                echo $this->render('flightzilla/index/partial/legend.phtml');
            ?>
        </div>
    </div>

    <div class="col-lg-10">
        <blockquote>
            <h3 class="table-toggle">Watchlist</h3>
        </blockquote>
        <form id="buglist-form" method="get" target="_blank" action="#" class="hide">
            <?php
            echo $this->partial('flightzilla/index/partial/table.phtml', array(
                'caption' => 'Watchlist',
                'sBugzilla' => $this->layout()->sBugzilla,
                'bugs' => $this->aWatchlist,
                'ready' => false,
                'mode' => $this->mode
            ));
            ?>
        </form>

        <?php
        foreach ($this->aProjects as $iTicket => $oProject) {
            /* @var \Flightzilla\Model\Ticket\Type\Bug $oProject */
            try {
                echo $this->partial('flightzilla/index/partial/table.phtml', array(
                    'captionTicket' => $oProject,
                    'sBugzilla'     => $this->layout()->sBugzilla,
                    'bugs'          => $oProject->getDependsAsStack(\Flightzilla\Model\Ticket\Type\Bug::STATUS_VERIFIED),
                    'ready'         => 'REVIEWED'
                ));
            }
            catch (\Flightzilla\Model\Ticket\Type\Bug\Exception $e) {
                echo sprintf('<div class="alert alert-danger">An Error occured when fetching the tickets for: %s</div>', $oProject->title());
            }
        }
        ?>
    </div>
</div>

<script type="text/javascript">
    /**
     * Add and remove tickets from watchlist
     */
    $('button.submitForm').click(function () {
        $(this).parents('form').submit();
    });
</script>
