<blockquote>
    <p><?php echo sprintf('%s %s (%s)', $this->ticketicons($this->oTicket), (string) $this->oTicket->short_desc, $this->oTicket->assignee_short); ?></p>
</blockquote>
<?php
echo $this->render('index/partial/flag.phtml');

foreach ($this->oTicket->long_desc as $oLongDesc):
?>
    <blockquote>
        <pre><?php echo (string) $oLongDesc->thetext ?></pre>
        <small><?php echo (string) $oLongDesc->who ?> @ <?php echo (string) $oLongDesc->bug_when ?></small>
    </blockquote>
<?php
endforeach;
?>
