<blockquote>
    <p><?php echo $this->oTicket->short_desc ?></p>
</blockquote>
<dl class="dl-horizontal">
    <?php
    foreach ($this->oTicket->getFlags() as $aFlag):
    ?>
        <dt><?php echo $aFlag['name'] ?></dt>
        <dd>
            <strong><?php echo $aFlag['status'] ?></strong>
            (by <?php echo $aFlag['setter']; ?>
            <?php if (empty($aFlag['requestee']) !== true) {
                echo sprintf('for %s', $aFlag['requestee']);
            }?>)
        </dd>
    <?php
    endforeach;
    ?>
</dl>
<?php
foreach ($this->oTicket->long_desc as $oLongDesc):
?>
    <blockquote>
        <pre><?php echo (string) $oLongDesc->thetext ?></pre>
        <small><?php echo (string) $oLongDesc->who ?> @ <?php echo (string) $oLongDesc->bug_when ?></small>
    </blockquote>
<?php
endforeach;
?>
