<div class="hero-unit">
    <form class="form-horizontal" method="POST" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'login'))?>">
        <legend>Login to <b><?php echo $this->sName; ?></b></legend>
        <fieldset>
            <div class="control-group">
                <label class="control-label" for="username">Username</label>
                <div class="controls">
                    <input type="text" name="username" />
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="password">Passwort</label>
                <div class="controls">
                    <input type="password" name="password" />
                </div>
            </div>

            <div class="control-group">
                <div class="controls">
                    <button class="btn btn-primary btn-large">Login</button>
                </div>
            </div>
        </fieldset>
    </form>

    <a href="https://github.com/hpbuniat/flightzilla"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>
</div>