<?php echo $this->render('index/partial/header.phtml')?>

<div class="row-fluid">
<?php
echo $this->render('index/partial/overview.phtml');
?>

<div class="span10">
<form method="get" target="_blank" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'go-bugzilla'))?>">

<h4 id="quickList" class="bugCount" style="display:none"></h4>
<?php
foreach ($this->aMemberBugs as $sName => $aBugs) {
    echo $this->partial('index/partial/table.phtml', array(
          'caption' => $sName,
          'sBugzilla' => $this->sBugzilla,
          'bugs' => $aBugs,
          'ready' => 'REVIEWED'
     ));
}
?>
</form>

</div>

<h4 id="quickList" class="bugCount" style="display:none"></h4>
</div>
