<tr class="bug <?php echo sprintf('ticket%s', $this->bug->id()); ?>"
    data-type="<?php echo ucfirst(strtolower($this->bug->getType())); ?>"
    data-assignee="<?php echo (string) $this->bug->getResource() ?>"
    data-component="<?php echo $this->bug->getComponent() ?>"
    style="<?php echo $this->buggradient($this->bug, $this->bReady);?>
">
    <td width="2%">
        <div class="priority priority-<?php echo strtolower($this->bug->priority) ?>"></div>
        <?php echo $this->bug->priority?>
    </td>
    <td width="15%">
        <a class="bugLink draggable" target="_blank" href="<?php echo $this->sBugzilla; ?>/show_bug.cgi?id=<?php echo $this->bug->id(); ?>" data-ticket="<?php echo $this->bug->id(); ?>"><?php echo $this->bug->id(); ?></a>
        &nbsp;
        <?php
        echo $this->bug->assignee_short;
        echo $this->ticketicons($this->bug);
        echo $this->deadlinestatus($this->bug);
        ?>
    </td>
    <?php if ($this->mode === 'project'):?>
        <td><?php echo (isset($this->aKanban[$this->bug->id()]) === true) ? \Flightzilla\Model\Kanban\Status::$aStatusText[$this->aKanban[$this->bug->id()]] : '-'; ?></td>
        <td><?php echo number_format($this->bug->getRevenue(), 0, '', '.'); ?></td>
        <td><?php echo $this->bug->getRevenueProbability(); ?></td>
        <td><?php echo $this->bug->getComplexity(); ?></td>
        <td><?php echo $this->bug->getRisk(); ?></td>
        <td><?php echo $this->bug->getDevelopmentTeam(); ?></td>
        <td><?php echo $this->bug->getActualTime(); ?></td>
        <td><?php echo $this->bug->getEstimation(); ?></td>
    <?php else: ?>
        <?php if (strlen($this->bug->resolution) == 0):?>
            <td colspan="2" width="10%" class="<?php echo $this->bug->getStatus(); ?>"><?php echo $this->bug->getStatus(); ?></td>
        <?php else:?>
            <td width="5%" class="<?php echo $this->bug->getStatus(); ?>"><?php echo substr($this->bug->getStatus(),0,4); ?></td>
            <?php if ((string) $this->bug->resolution === \Flightzilla\Model\Ticket\Type\Bug::RESOLUTION_DUPLICATE): ?>
                <td width="5%">
                    <a class="bugLink tipper" target="_blank" data-title="<?php echo $this->escapeHtml($this->bug->getDupe()); ?>" href="<?php echo $this->layout()->sBugzilla; ?>/show_bug.cgi?id=<?php echo $this->bug->getDupe(); ?>"><?php echo substr($this->bug->resolution,0,6); ?></a>
                </td>
            <?php else: ?>
                <td width="5%"><?php echo substr($this->bug->resolution,0,6); ?></td>
            <?php endif; ?>
        <?php endif?>
        <td width="8%">
            <?php echo $this->estimation($this->bug); ?>
        </td>
    <?php endif; ?>
    <td class="bugDesc" data-release="<?php echo $this->escapeHtml($this->bug->getReleaseNote()); ?>" width="50%"><?php echo $this->escapeHtml($this->bug->title()); ?></td>
    <td width="2%">
        <input class="<?php echo $this->workflow($this->bug); ?>" type="checkbox" name="id[]" value="<?php echo $this->bug->id(); ?>"/>
    </td>
    <td class="bugProd" width="13%">
        <?php echo substr($this->bug->component, 0, 8)?> <?php if ($this->bug->getVersion() !== '') { echo '(' . $this->bug->getVersion() . ')'; } ?>
        <span class="pull-right">
            <a href="javascript:;" data-ticket="<?php echo $this->bug->id(); ?>" class="ticket-detail glyphicon glyphicon-list"></a>
        </span>
    </td>
    <td class="data-toggler data-toggle toggle-create" data-toggle="create"
        data-toggle-short="<?php echo date('y/W', $this->bug->getCreationTime()); ?>"
        data-toggle-long="<?php echo date('Y-m-d', $this->bug->getCreationTime()); ?>"></td>
    <td class="data-toggler data-toggle toggle-update" data-toggle="update"
        data-toggle-short="<?php echo date('y/W', ($this->mode === 'project') ? $this->bug->getLastActivityOfDependencies() : $this->bug->getLastActivity()); ?>"
        data-toggle-long="<?php echo date('Y-m-d', ($this->mode === 'project') ? $this->bug->getLastActivityOfDependencies() : $this->bug->getLastActivity()); ?>"></td>
</tr>
