<tr class="bug"
    data-type="<?php echo ucfirst(strtolower($this->bug->getType())); ?>"
    data-assignee="<?php echo (string) $this->bug->getResource() ?>"
    data-component="<?php echo $this->bug->getComponent() ?>"
    style="<?php echo $this->buggradient($this->bug, $this->bReady);?>
">
    <td width="2%">
        <?php echo $this->bug->priority?>
    </td>
    <td width="11%">
        <a class="bugLink" target="_blank" href="<?php echo $this->sBugzilla; ?>/show_bug.cgi?id=<?php echo $this->bug->id(); ?>"><?php echo $this->bug->id(); ?></a>
        &nbsp;
        <?php
        echo $this->bug->assignee_short;
        echo $this->ticketicons($this->bug);
        echo $this->deadlinestatus($this->bug);
        ?>
    </td>
    <?php if (strlen($this->bug->resolution) == 0):?>
        <td colspan="2" width="10%" class="<?php echo $this->bug->getStatus(); ?>"><?php echo $this->bug->getStatus(); ?></td>
    <?php else:?>
        <td width="5%" class="<?php echo $this->bug->getStatus(); ?>"><?php echo substr($this->bug->getStatus(),0,4); ?></td>
        <td width="5%"><?php echo substr($this->bug->resolution,0,6); ?></td>
    <?php endif?>
    <td width="8%">
        <?php echo $this->estimation($this->bug); ?>
    </td>
    <td class="bugDesc" width="50%"><?php echo $this->escapeHtml($this->bug->title())?></td>
    <td width="2%">
        <input class="<?php echo $this->workflow($this->bug); ?>" type="checkbox" name="id[]" value="<?php echo $this->bug->id(); ?>"/>
    </td>
    <td class="bugProd" width="17%">
        <?php echo substr($this->bug->component,0,8)?> <?php if($this->bug->version != 'unspecified') { echo '(' . $this->bug->version . ')'; } ?>
        <span class="pull-right">
            <a href="javascript:;" data-ticket="<?php echo $this->bug->id(); ?>" class="ticket-detail icon-list"></a>
        </span>
    </td>
</tr>
