<?php
    $aStack = $this->userfilter($this->aDeadlineStack, $this->sMemberName);
    if (empty($aStack) !== true):
?>
<blockquote>
    <h3>Your tickets with deadlines</h3>
</blockquote>
<?php
    foreach ($aStack as $iDeadline => $aTickets) {
        echo $this->partial('flightzilla/index/partial/table.phtml', array(
            'caption' => sprintf('Deadline at: %s', date('d.m.Y', $iDeadline)),
            'sBugzilla' => $this->layout()->sBugzilla,
            'bugs' => $aTickets,
            'ready' => \Flightzilla\Model\Ticket\Type\Bug::STATUS_REVIEWED
        ));
    }

    endif;
