<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="#">flightzilla</a>
            <div class="nav-collapse pull-right">
              <ul class="nav">
                <li><a href="javascript:window.location.reload()"><i class="icon-refresh icon-white"></i> Refresh</a></li>
                <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'logout'))?>"><i class="icon-off icon-white"></i> Sign Out</a></li>
              </ul>
            </div>
            <div class="nav-collapse">
                <ul class="nav">
                    <li class="<?php echo ($this->mode === 'dashboard') ? 'active' : ''; ?>"><a href="<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'dashboard'))?>">My Tickets</a></li>
                    <li class="<?php echo ($this->mode === 'board') ? 'active' : ''; ?>"><a href="<?php echo $this->url('flightzilla', array('controller' => 'kanban', 'action' => 'board'))?>">Board</a></li>
                    <li class="<?php echo ($this->mode === 'list') ? 'active' : ''; ?>"><a href="<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'index'))?>">Bugs</a></li>
                    <li class="dropdown <?php echo ($this->mode === 'team') ? 'active' : ''; ?>">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Team
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'teamdash'))?>">Team-Dashboard</a></li>
                            <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'team'))?>">Team-List</a></li>
                            <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'summary'))?>">Summary</a></li>
                        </ul>
                    </li>
                    <li class="dropdown <?php echo ($this->mode === 'planning') ? 'active' : ''; ?>">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Planning
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'planning', 'action' => 'projects'))?>">Projects</a></li>
                            <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'planning', 'action' => 'sprint'))?>">Resources</a></li>
                        </ul>
                    </li>
                    <li class="<?php echo ($this->mode === 'mergy') ? 'active' : ''; ?>"><a href="<?php echo $this->url('flightzilla', array('controller' => 'mergy', 'action' => 'index'))?>">Mergy</a></li>
                    <li class="<?php echo ($this->mode === 'analytics') ? 'active' : ''; ?>"><a href="<?php echo $this->url('flightzilla', array('controller' => 'analytics', 'action' => 'index'))?>">Analytics</a></li>
                    <li class="divider"></li>
                </ul>
                <form class="navbar-search">
                    <input type="text" id="searchId" value="Search" onblur="if (this.value=='') { this.value='Search'; }" onfocus="if (this.value=='Search') { this.value=''; }" class="" />
                </form>
            </div>
        </div>
    </div>
</div>
