<?php
/* get the view-model of the controller */
$aViewModels = $this->viewModel()->getCurrent()->getChildren();
$oControllerViewModel = reset($aViewModels);
?>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">flightzilla</a>
    </div>

    <div class="nav-collapse collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
            <li class="dropdown <?php echo ($oControllerViewModel->mode === 'dashboard') ? 'active' : ''; ?>">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Dashboard
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'dashboard')); ?>">My Dashboard</a></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'mytickets')); ?>">My Tickets</a></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'watchlist', 'action' => 'index')); ?>">My Watchlist</a></li>
                    <li class="divider"></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'conflicts')); ?>">Conflicts</a></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'stats', 'action' => 'index')); ?>">Stats</a></li>
                </ul>
            </li>
            <li class="<?php echo ($oControllerViewModel->mode === 'board') ? 'active' : ''; ?>"><a href="<?php echo $this->url('flightzilla', array('controller' => 'kanban', 'action' => 'board')); ?>">Board</a></li>
            <li class="<?php echo ($oControllerViewModel->mode === 'list') ? 'active' : ''; ?>"><a href="<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'index')); ?>">Tickets</a></li>
            <li class="dropdown <?php echo ($oControllerViewModel->mode === 'team') ? 'active' : ''; ?>">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Team
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'team', 'action' => 'dashboard')); ?>">Dashboard</a></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'team', 'action' => 'index')); ?>">Ticket-List</a></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'team', 'action' => 'sprint')); ?>">Weekly Sprints</a></li>
                    <li class="divider"></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'team', 'action' => 'summary')); ?>">Summary</a></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'team', 'action' => 'review')); ?>">Review</a></li>
                </ul>
            </li>
            <li class="dropdown <?php echo ($oControllerViewModel->mode === 'project') ? 'active' : ''; ?>">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Projects
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'project', 'action' => 'dashboard')); ?>">My Projects</a></li>
                    <li class="divider"></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'project', 'action' => 'index')); ?>">List</a></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'project', 'action' => 'board')); ?>">Board</a></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'project', 'action' => 'list')); ?>">Ticket-List</a></li>
                    <li class="divider"></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'project', 'action' => 'planning')); ?>">Planning</a></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'project', 'action' => 'planning', 'detailed' => 'detailed')); ?>">Planning (Detailed)</a></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'project', 'action' => 'resources')); ?>">Resources</a></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'project', 'action' => 'graph')); ?>">Graph</a></li>
                </ul>
            </li>
            <li class="dropdown <?php echo ($oControllerViewModel->mode === 'sourcecode') ? 'active' : ''; ?>">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Source
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'mergy', 'action' => 'index')); ?>">Merge</a></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'mergy', 'action' => 'status')); ?>">Status</a></li>
                    <li class="divider"></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'source', 'action' => 'index')); ?>">Review</a></li>
                </ul>
            </li>
            <li class="dropdown <?php echo ($oControllerViewModel->mode === 'analytics') ? 'active' : ''; ?>">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Analytics
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'analytics', 'action' => 'campaign')); ?>">Campaigns</a></li>
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'analytics', 'action' => 'browser')); ?>">Browser</a></li>
                </ul>
            </li>
            <li class="divider"></li>
        </ul>

        <form class="navbar-form pull-left">
            <input class="form-control col-lg-8" type="text" id="searchId" value="Search" onblur="if (this.value=='') { this.value='Search'; }" onfocus="if (this.value=='Search') { this.value=''; }" class="" />
        </form>
        <ul class="nav navbar-nav pull-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <?php echo $this->layout()->sCurrentProject; ?>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <?php $aProjects = $this->layout()->aConfigProjects;
                    if (is_array($aProjects) === true):
                        foreach ($aProjects as $sConfigProjects): ?>
                            <li><a href="<?php echo $this->url('flightzilla/default', array('controller' => 'index', 'action' => 'setproject', 'project' => $sConfigProjects)); ?>"><?php echo $sConfigProjects; ?></a></li>
                        <?php endforeach;
                    endif; ?>
                </ul>
            </li>
            <li class="tipper" data-title="Refresh"><a class="refresh-button" href="#"><i class="glyphicon glyphicon-refresh glyphicon-white"></i></a></li>
            <li class="dropdown tipper" data-title="<?php echo $this->layout()->sCurrentUser; ?>">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="glyphicon glyphicon-user glyphicon-white"></i>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'logout')); ?>"><i class="glyphicon glyphicon-off"></i> Sign Out</a></li>
                </ul>
            </li>
            <li id="dStatus" data-data="<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'status')); ?>">
                <?php echo $this->render('flightzilla/index/status.phtml'); ?>
            </li>
        </ul>
    </div>
</nav>
