<ul class="nav nav-list">
    <li class="nav-header"><a href="javascript:;" data-target="legend" class="toggle">Legend</a></li>
    <li class="legend">
        <div style="background-color: <?php echo \Flightzilla\View\Helper\Buggradient::COLOR_TEST_FAILED; ?>;">Test denied!</div>
    </li>
    <li class="legend">
        <div style="background-color: <?php echo \Flightzilla\View\Helper\Buggradient::COLOR_TESTING; ?>;">Testing open</div>
    </li>
    <li class="legend">
        <div style="background-color: <?php echo \Flightzilla\View\Helper\Buggradient::COLOR_PARTIALLY_TESTED; ?>;">Partially tested (Testing or Reporter)</div>
    </li>
    <li class="legend">
        <div style="background-color: <?php echo \Flightzilla\View\Helper\Buggradient::COLOR_TESTED; ?>;">Tested (Testing &amp; Reporter)</div>
    </li>
    <li class="legend">
        <div style="background-color: <?php echo \Flightzilla\View\Helper\Buggradient::COLOR_MERGE_REQUEST; ?>;">Merge-Request</div>
    </li>
    <li class="legend">
        <div style="background-color: <?php echo \Flightzilla\View\Helper\Buggradient::COLOR_DB_CHANGE; ?>;">DB-Change</div>
    </li>
    <li class="legend">
        <div style="background-color: <?php echo \Flightzilla\View\Helper\Buggradient::COLOR_TRANSLATION_REQUEST; ?>;">Translation-Request</div>
    </li>
    <li class="legend">
        <div style="background-color: <?php echo \Flightzilla\View\Helper\Buggradient::COLOR_SCREEN_REQUEST; ?>;">Awaiting Test/Screen-Approval</div>
    </li>
    <li class="legend">
        <div style="background-color: <?php echo \Flightzilla\View\Helper\Buggradient::COLOR_PRODUCT_DEPENDENCY; ?>; color: white;">Product dependency!</div>
    </li>

    <li class="legend"><i class="glyphicon glyphicon-random"></i> Mergable</li>
    <li class="legend"><i class="glyphicon glyphicon-plus-sign"></i> Merged</li>
    <li class="legend"><i class="glyphicon glyphicon-comment"></i> Waiting for a Comment</li>
    <li class="legend"><i class="glyphicon glyphicon-eye-open"></i> Awaiting Test/Screen-Approval</li>
    <li class="legend"><i class="glyphicon glyphicon-thumbs-up"></i> Testing/Screen approved</li>
    <li class="legend"><i class="glyphicon glyphicon-camera"></i> Ticket on watchlist</li>
    <li class="legend"><i class="glyphicon glyphicon-link"></i> Dependency to another Product</li>
    <li class="legend"><span class="red">i18n </span> Translation done</li>
    <li class="legend"><span class="ui-silk ui-silk-bug">&nbsp;</span> Ticket is a Bug</li>
    <li class="legend"><span class="ui-silk ui-silk-database-refresh">&nbsp;</span> DB-Change done</li>
    <li class="legend"><span class="ui-silk ui-silk-flag-yellow">&nbsp;</span> Deadline</li>
</ul>
