<?php
$aTimes = $this->collectiontime($this->aStack);
$sEstimationString = sprintf('%sh (%sh est.) <i class="icon-time"></i> %sh (%sd)', $aTimes['spent'], $aTimes['esti'] , $aTimes['left'] ,$aTimes['days']);
?>
<div class="row-fluid memberBox">
    <div class="span12 well">
        <div class="span2">
            <a href="#" class="thumbnail">
                <?php
                    echo $this->gravatar($this->oResourceManager->getResource($this->sMemberName)->getGravatar(), array(
                        'imgSize' => 90,
                        'secure' => true
                    ),
                    array(
                        'class' => 'avatar',
                        'title' => $this->sMemberName
                    ));
                ?>
            </a>
            <?php echo sprintf('<h5><strong>%s</strong></h5>', $this->sMemberName); ?>
        </div>
        <div class="span10">
            <div class="row-fluid">
                <div class="span3">
                    <blockquote>
                        <p><?php echo $sEstimationString; ?></p>
                    </blockquote>
                </div>
                <div class="span9">
                    <div title="<?php echo $sEstimationString; ?>" class="progress progress-<?php echo $aTimes['color'];?> progress-striped">
                        <div class="bar" style="width: <?php echo $aTimes['future']; ?>%"></div>
                    </div>
                </div>
            </div>
            <?php
                $this->iSplit = 9;
                echo $this->render('flightzilla/index/partial/pin-row.phtml');
            ?>
        </div>
    </div>
</div>
