<div class="span2">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Status</li>
      <li><a href="javascript:;" data-target="all" class="toggleBugs">Total: <?php echo $this->iTotal?> Bugs</a></li>
        <?php if (empty($this->aStatuses) !== true):
            foreach ($this->aStatuses as $sType => $aStatus): ?>
        <?php if ($aStatus['num'] > 0): ?>
            <li><a href="javascript:;" data-target="<?php echo $sType?>" class="toggleBugs <?php echo $sType?>">
                <?php echo ucwords(strtolower($sType))?>: <?php echo $aStatus['num']?> (<?php echo ceil($aStatus['per'])?>%)
            </a></li>
        <?php endif; ?>
        <?php endforeach; endif; ?>
      <li class="nav-header">Workflow</li>
        <?php if (empty($this->aStats) !== true):
            foreach ($this->aStats as $sType => $aStatus): ?>
        <?php if ($aStatus['num'] > 0): ?>
            <li><a href="javascript:;" data-target="<?php echo $sType?>" class="toggleBugs <?php echo $sType?>">
                <?php echo ucwords(strtolower($sType))?>: <?php echo $aStatus['num']?> (<?php echo ceil($aStatus['per'])?>%)
            </a></li>
        <?php endif; ?>
        <?php endforeach; endif; ?>
      <li class="nav-header">Priorities</li>
        <?php if (empty($this->aPriorities) !== true):
            foreach ($this->aPriorities as $sType => $aStatus): ?>
        <?php if ($aStatus['num'] > 0): ?>
            <li><a href="javascript:;" data-target="prio<?php echo $sType?>" class="toggleBugs prio<?php echo $sType?>">
                <?php echo ucwords(strtolower($sType))?>: <?php echo $aStatus['num']?> (<?php echo ceil($aStatus['per'])?>%)
            </a></li>
        <?php endif; ?>
        <?php endforeach; endif; ?>

        <li class="nav-header">Severities</li>
        <?php if (empty($this->aSeverities) !== true):
                foreach ($this->aSeverities as $sType => $aStatus): ?>
        <?php if ($aStatus['num'] > 0): ?>
            <li><a href="javascript:;" data-target="severity<?php echo $sType?>" class="toggleBugs severity<?php echo $sType?>">
                <?php echo ucwords(strtolower($sType))?>: <?php echo $aStatus['num']?> (<?php echo ceil($aStatus['per'])?>%)
            </a></li>
        <?php endif; ?>
        <?php endforeach; endif; ?>

        <li class="nav-header"><a href="javascript:;" data-target="legend" class="toggle">Legende</a></li>
        <li class="legend"><div style="background-color: crimson; padding: 8px;">Test nicht bestanden!</div></li>
        <li class="legend"><div style="background-color: yellow; padding: 8px;">Test offen</div></li>
        <li class="legend"><div style="background-color: #CCFF99; padding: 8px;">Teilweise getestet (Testing o. Reporter)</div></li>
        <li class="legend"><div style="background-color: lightgreen; padding: 8px;">Getestet (Testing &amp; Reporter)</div></li>
        <li class="legend"><div style="background-color: #9FB9FF; padding: 8px;">Merge-Request</div></li>
        <li class="legend"><div style="background-color: orchid; padding: 8px;">DB-Change</div></li>
        <li class="legend"><div style="background-color: orange; padding: 8px;">Translation-Request</div></li>
        <li class="legend"><div style="background-color: #9F9F9F; padding: 8px;">Screen-Abnahme offen</div></li>
        <li class="legend"><span class="red">M </span> Bug gemergt</li>
        <li class="legend"><span class="ui-silk ui-silk-exclamation">&nbsp;</span> R&uuml;ckfrage</li>
        <li class="legend"><span class="ui-silk ui-silk-thumb-up">&nbsp;</span> Screen abgenommen</li>
        <li class="legend"><span class="red">i18n </span> &Uuml;bersetzung fertig</li>
        <li class="legend"><span class="ui-silk ui-silk-database-refresh">&nbsp;</span> DB-Change erfolgt</li>
        <li class="legend"><span class="ui-silk ui-silk-flag-yellow">&nbsp;</span> Deadline</li>
    </ul>
  </div>
    <?php if (isset($this->sChuck) === true):?>
    <img class="chuck" src="<?php echo $this->basePath() . '/images/chuck/' . $this->sChuck; ?>" />
    <?php endif;?>
</div>
