<div class="col-lg-2">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Status</li>
      <li><a href="javascript:;" data-target="all" class="toggleBugs">Total: <?php echo $this->iTotal?> Bugs</a></li>
        <?php if (empty($this->aStatuses) !== true):
            foreach ($this->aStatuses as $sType => $aStatus): ?>
        <?php if ($aStatus['num'] > 0): ?>
            <li><a href="javascript:;" data-target="<?php echo $sType?>" class="toggleBugs <?php echo $sType?>">
                <?php echo ucwords(strtolower($sType))?>: <?php echo $aStatus['num']?> (<?php echo ceil($aStatus['per'])?>%)
            </a></li>
        <?php endif; ?>
        <?php endforeach; endif; ?>
      <li class="nav-header">Workflow</li>
        <?php if (empty($this->aStats) !== true):
            foreach ($this->aStats as $sType => $aStatus): ?>
        <?php if ($aStatus['num'] > 0): ?>
            <li><a href="javascript:;" data-target="<?php echo $sType?>" class="toggleBugs <?php echo $sType?>">
                <?php echo str_replace('-', ' ', ucwords(strtolower($sType))); ?>: <?php echo $aStatus['num']?> (<?php echo ceil($aStatus['per'])?>%)
            </a></li>
        <?php endif; ?>
        <?php endforeach; endif; ?>
      <li class="nav-header">Priorities</li>
        <?php if (empty($this->aPriorities) !== true):
            foreach ($this->aPriorities as $sType => $aStatus): ?>
        <?php if ($aStatus['num'] > 0): ?>
            <li><a href="javascript:;" data-target="prio<?php echo $sType?>" class="toggleBugs prio<?php echo $sType?>">
                    <?php echo str_replace('-', ' ', ucwords(strtolower($sType))); ?>: <?php echo $aStatus['num']?> (<?php echo ceil($aStatus['per'])?>%)
            </a></li>
        <?php endif; ?>
        <?php endforeach; endif; ?>

        <li class="nav-header">Severities</li>
        <?php if (empty($this->aSeverities) !== true):
                foreach ($this->aSeverities as $sType => $aStatus): ?>
        <?php if ($aStatus['num'] > 0): ?>
            <li><a href="javascript:;" data-target="severity<?php echo $sType?>" class="toggleBugs severity<?php echo $sType?>">
                    <?php echo str_replace('-', ' ', ucwords(strtolower($sType))); ?>: <?php echo $aStatus['num']?> (<?php echo ceil($aStatus['per'])?>%)
            </a></li>
        <?php endif; ?>
        <?php endforeach; endif; ?>

        <li class="nav-header">Created before</li>
        <?php if (empty($this->aDaysCreated) !== true):
            foreach ($this->aDaysCreated as $sType => $aStatus): ?>
                <?php if ($aStatus['num'] > 0): ?>
                    <li><a href="javascript:;" data-target="created<?php echo $sType?>" class="toggleBugs created<?php echo $sType?>">
                            <?php echo str_replace('-', ' ', ucwords(strtolower($sType))); ?> days: <?php echo $aStatus['num']?> (<?php echo ceil($aStatus['per'])?>%)
                        </a></li>
                <?php endif; ?>
            <?php endforeach; endif; ?>

        <li class="nav-header">Active before</li>
        <?php if (empty($this->aDaysActive) !== true):
            foreach ($this->aDaysActive as $sType => $aStatus): ?>
                <?php if ($aStatus['num'] > 0): ?>
                    <li><a href="javascript:;" data-target="active<?php echo $sType?>" class="toggleBugs active<?php echo $sType?>">
                            <?php echo str_replace('-', ' ', ucwords(strtolower($sType))); ?> days: <?php echo $aStatus['num']?> (<?php echo ceil($aStatus['per'])?>%)
                        </a></li>
                <?php endif; ?>
            <?php endforeach; endif; ?>
    </ul>
    <?php
      echo $this->render('flightzilla/index/partial/legend.phtml');
    ?>
  </div>
    <?php if (isset($this->sChuck) === true):?>
    <img class="chuck" src="<?php echo $this->basePath() . '/img/chuck/' . $this->sChuck; ?>" />
    <?php endif;?>
</div>
