<div class="row-fluid">
    <?php
    $aPins = array(
        'active' => '',
        'pending' => '',
        'not' => ''
    );

    $iActive = $iShowed = 0;
    $bHasDevelopment = $this->oProject->hasDevelopment();
    $bIsMerged = $this->oProject->isMerged();

    foreach ($this->aStack as $this->oTicket) {
        $sRender = $this->render('flightzilla/kanban/partial/pin.phtml');
        if ($this->oTicket->isWip() === true) {
            $iActive++;
            $aPins['active'] .= $sRender;
        }
        elseif ($iShowed < $this->iLimit and $this->oTicket->isStatusAtLeast(\Flightzilla\Model\Ticket\Type\Bug::STATUS_RESOLVED) !== true) {
            $iShowed++;
            $aPins['pending'] .= $sRender;
        }
        else {
            $aPins['not'] .= $sRender;
        }
    }

    $this->iSplit = ($this->sRowMode ==  'project' and $iActive === 0 and $iShowed === 0) ? 6 : $this->iSplit;

    ?>
    <div class="span<?php echo (11 - $this->iSplit); ?>">
        <?php if ($this->sRowMode ==  'project' and $iActive === 0 and $iShowed === 0): ?>
            <?php if ($bHasDevelopment === false): ?>
                <div class="alert alert-error">
                    There are no development-tickets for this project!
                </div>
            <?php else: ?>
                <?php if ($bIsMerged === true): ?>
                    <div class="alert alert-success">
                        This project will be part of the next release!
                    </div>
                <?php else: ?>
                    <div class="alert alert-success">
                        <strong>Well done!</strong> No tickets left!
                    </div>
                <?php endif;?>
            <?php endif;?>
        <?php else:?>
            <img alt="lazy" src="<?php echo $this->basePath() . '/img/lazy.png'; ?>" class="lazy <?php echo ($iActive === 0) ? '' : 'hidden'; ?>" />
            <?php echo $aPins['active']; ?>
        <?php endif;?>
    </div>
    <div class="span1 relative-box">
        <strong class="largeGray"><?php echo count($this->aStack);?> <br/> ...</strong>
    </div>
    <div class="span<?php echo $this->iSplit; ?> pending">
        <?php echo $aPins['pending']; ?>
        <div class="hidden allTickets">
            <?php echo $aPins['not']; ?>
        </div>
    </div>
</div>
