<div class="row-fluid">
    <?php
    $aPins = array(
        'active' => '',
        'pending' => '',
        'not' => ''
    );

    $iActive = $iShowed = 0;
    foreach ($this->aStack as $this->oTicket) {
        $sRender = $this->render('flightzilla/kanban/partial/pin.phtml');
        if ($this->oTicket->isWip() === true) {
            $iActive++;
            $aPins['active'] .= $sRender;
        }
        elseif ($iShowed < $this->iSplit and $this->oTicket->isStatusAtLeast(\Flightzilla\Model\Ticket\Type\Bug::STATUS_RESOLVED) !== true) {
            $iShowed++;
            $aPins['pending'] .= $sRender;
        }
        else {
            $aPins['not'] .= $sRender;
        }
    }
    ?>
    <div class="span<?php echo (11 - $this->iSplit); ?>">
        <?php if ($this->sRowMode ==  'project' and $iActive === 0 and $iShowed === 0): ?>
            <div class="alert alert-success">
                <strong>Well done!</strong> No tickets left!
            </div>
        <?php else:?>
            <img alt="lazy" src="<?php echo $this->basePath() . '/img/lazy.png'; ?>" class="lazy <?php echo ($iActive === 0) ? '' : 'hidden'; ?>" />
            <?php echo $aPins['active']; ?>
        <?php endif;?>
    </div>
    <div class="span1 relative-box">
        <strong class="largeGray"><?php echo count($this->aStack);?> <br/> ...</strong>
    </div>
    <div class="span<?php echo $this->iSplit; ?> pending">
        <?php echo $aPins['pending']; ?>
        <div class="hidden allTickets">
            <?php echo $aPins['not']; ?>
        </div>
    </div>
</div>
