<?php
if (empty($this->bugs) === true) {
    $this->bugs = array();
}

if (empty($this->sCssClass) === true) {
    $this->sCssClass = '';
}

$aTimes = $this->collectiontime($this->bugs);

if(count($this->bugs) > 0) {?>
<table class="bugTable table-bordered table-condensed table tablesorter <?php echo $this->sCssClass; ?>" style="width: 100%; margin-bottom: 10px;">
    <thead>
    <tr class="tableHeader">
        <td colspan="8">
            <span class="caption <?php if ($this->mode === 'team' and $aTimes['left'] < \Flightzilla\Model\Timeline\Date::AMOUNT):?>red<?php endif;?>">
                <b><?php echo $this->caption; ?> (<?php echo count($this->bugs); ?>)</b>
                <?php echo $aTimes['spent'];?>h worked (<?php echo $aTimes['esti']; ?>h estimated) - Left: <?php echo $aTimes['left']; ?>h / <?php echo $aTimes['days']; ?>d
            </span>
            <div class="btn-group pull-right">
                <a class="allBugs btn btn-small" href="javascript:;">All</a>
                <a class="noBugs btn btn-small" href="javascript:;">None</a>
                <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
                    Ticket-List
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#" class="changelist">Release-List (Trac)</a></li>
                    <li><a href="#" class="changemail">Release-List (Mail)</a></li>
                    <li><a href="#" class="mergelist">Merge-List</a></li>
                    <li class="divider"></li>
                    <li><a href="#" class="print-link">Print-View</a></li>
                    <li><a href="#" class="bugzilla-link">Open in Bugzilla</a></li>
                    <li class="divider"></li>
                    <li><a href="#" class="modify-tickets">Modify Tickets</a></li>
                </ul>
            </div>
        </td>
    </tr>

    <tr class="tableHeader">
        <th>Prio</th>
        <th>Bug No.</th>
        <th>Resolution</th>
        <th>Status</th>
        <th class="{sorter: 'digit'}">Times</th>
        <th>Summary</th>
        <th></th>
        <th>Component</th>
    </tr>
    </thead>
    <tbody>
    <?php
        foreach($this->bugs as $bug) {
            $this->bug = $bug;
            $this->bReady = ($this->ready !== false and $bug->resolution === $this->ready);
            echo $this->render('flightzilla/index/partial/bug.phtml');
        }
    ?>
    </tbody>
</table>
<?php
}
