<div class="col-lg-6">
    <div class="callout callout-warning">
        <h3><?php echo $this->aItems['description']; ?></h3>
    </div>
    <?php
    if (empty($this->aItems['stack']) === true) {
        ?>
        <div class="alert alert-success">
          <strong>Well done!</strong> Nothing to do here.
        </div>
<?php
    }
    else {
        foreach ($this->aItems['stack'] as $oTicket) {
            $this->oTask = $oTicket;
            echo sprintf('<p>%s</p>', $this->render('flightzilla/index/partial/bug-line.phtml'));
        }
    }
    ?>
</div>
<?php
    if (isset($this->iColumnCount) === true and $this->iColumnCount == 1) {
        $this->iColumnCount = 0;
        echo '</div><div class="row">';
    }
    else {
        $this->iColumnCount = 1;
    }
?>

