<?php
    $bReady = ($this->ready !== false and $this->oTicket->resolution === $this->ready);
?>
<div data-ticket="<?php echo $this->oTicket->id(); ?>" class="pin draggable <?php echo sprintf('ticket%s', $this->oTicket->id()); ?>" style="<?php echo $this->buggradient($this->oTicket, $bReady, false); ?>">
    <div class="pin-top label <?php echo $this->prioritycolor($this->oTicket); ?>">
        <span class="pull-left">
        <?php
            echo $this->ticketicons($this->oTicket);
            echo $this->deadlinestatus($this->oTicket);
        ?>
        </span>
        <span class="pull-right">
            <a href="javascript:;" data-ticket="<?php echo $this->oTicket->id(); ?>" class="ticket-detail icon-list"></a>
        </span>
    </div>
    <div class="description">
        <a class="bugLink" target="_blank" data-title="<?php echo $this->escapeHtml($this->oTicket->title()); ?>" href="<?php echo $this->layout()->sBugzilla; ?>/show_bug.cgi?id=<?php echo $this->oTicket->bug_id; ?>"><?php echo $this->escapeHtml($this->oTicket->title())?></a>
    </div>
    <div class="pin-bottom">
        <?php
        echo $this->estimation($this->oTicket, 'board');

        $iContainer = $this->oTicket->getContainer();
        if (empty($iContainer) !== true):
            $sTitle = (isset($this->aThemes[$iContainer]) === true) ? $this->aThemes[$iContainer] : '';
            ?>
            <span class="pull-left theme label label-info">
                <a class="bugLink" target="_blank" data-title="<?php echo $this->escapeHtml($sTitle); ?>" href="<?php echo $this->layout()->sBugzilla; ?>/show_bug.cgi?id=<?php echo $iContainer; ?>"><?php echo $iContainer; ?></a>
            </span>
            <?php
        endif;
        ?>
    </div>
</div>
