<?php
    $bReady = ($this->ready !== false and $this->oTicket->resolution === $this->ready);
?>
<div class="pin" style="<?php echo $this->buggradient($this->oTicket, $bReady, false);?>">
    <div class="top label <?php echo $this->prioritycolor($this->oTicket); ?>">
        <?php
        echo $this->ticketicons($this->oTicket);
        echo $this->deadlinestatus($this->oTicket);
        ?>
    </div>
    <div class="description">
        <a class="bugLink" target="_blank" data-title="<?php echo $this->escapeHtml($this->oTicket->title())?>" href="<?php echo $this->layout()->sBugzilla; ?>/show_bug.cgi?id=<?php echo $this->oTicket->bug_id?>"><?php echo $this->escapeHtml($this->oTicket->title())?></a>
    </div>
    <div class="bottom">
        <?php
        echo $this->estimation($this->oTicket, 'board');
        if ($this->oTicket->getStatus() === \Flightzilla\Model\Ticket\Type\Bug::STATUS_UNCONFIRMED or $this->oTicket->getStatus() === \Flightzilla\Model\Ticket\Type\Bug::STATUS_NEW):
            ?>
            <span class="pull-left status label label-success">NEW</span>
            <?php
        endif;

        $iTheme = $this->oTicket->getTheme();
        if (empty($iTheme) !== true):
            ?>
            <span class="pull-left theme label label-info">
                            <a class="bugLink" target="_blank" data-title="<?php echo $this->escapeHtml($this->aThemes[$iTheme]); ?>" href="<?php echo $this->layout()->sBugzilla; ?>/show_bug.cgi?id=<?php echo $iTheme; ?>"><?php echo $iTheme; ?></a>
                        </span>
            <?php
        endif;
        ?>
    </div>
</div>
