<div class="row">
    <?php echo $this->render('flightzilla/index/partial/overview.phtml'); ?>

    <div class="col-lg-10">
        <form id="buglist-form" method="get" target="_blank" action="#">
            <?php
            echo $this->partial('flightzilla/index/partial/table.phtml', array(
                'caption' => 'Tickets with unmerged revisions',
                'sBugzilla' => $this->layout()->sBugzilla,
                'bugs' => $this->aAllTickets,
                'revisions' => $this->oMergy,
                'ready' => 'REVIEWED',
                'oTicketService' => $this->oTicketService
            ));
            ?>
        </form>

        <p>
            <a class="btn btn-lg commit merge-button" href="javascript:;">Merge & Commit</a>
            <a class="btn btn-primary btn-lg merge-button" href="javascript:;">Merge</a>
        </p>
        <div id="container" data-repos='<?php echo $this->sRepositories?>'></div>
    </div>

    <h4 id="quickList" class="bugCount" style="display:none"></h4>
</div>
