<div class="row">
<?php
echo $this->render('flightzilla/index/partial/overview.phtml');
?>

<div class="col-lg-10">
<form id="buglist-form" method="get" target="_blank" action="#">
<?php
foreach ($this->aMemberBugs as $sName => $aBugs) {
    echo $this->partial('flightzilla/index/partial/table.phtml', array(
          'caption' => $sName,
          'sBugzilla' => $this->layout()->sBugzilla,
          'bugs' => $aBugs,
          'ready' => \Flightzilla\Model\Ticket\Type\Bug::STATUS_RESOLVED,
          'mode' => $this->mode
     ));
}
?>
</form>

</div>

<h4 id="quickList" class="bugCount" style="display:none"></h4>
</div>
