<div class="clearfix member-background">
<?php
    $this->bThumbnail = false;
    foreach ($this->aTeam as $aTeam) {
        $this->sMemberName = $aTeam['name'];
        $this->oResource = $this->oResourceManager->getResource($this->sMemberName);
        echo sprintf('<div class="pull-left member-layer">%s</div>', $this->render('flightzilla/team/partial/member.phtml'));
    }
?>
    <p class="pull-right droppable close-tickets">
        <button type="button" class="close">&times;</button>
    </p>
</div>
