<div class="row">
    <div class="hidden" id="ganttGraph">

    </div>

    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/jquery.fn.gantt.js'); ?>
    <script type="text/javascript">
        $(function() {
            var $gantt = $("#ganttGraph");
            $gantt.gantt({
                source: <?php echo $this->sResource; ?>,
                navigate: "scroll",
                scale: "hours",
                maxScale: "weeks",
                minScale: "hours",
                dow: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
                itemsPerPage: 100,
                hourRange: {
                    from: 7,
                    to: 21
                },
                scrollToToday: true
            });

            $gantt.removeClass('hidden');
        });
    </script>
</div>
