<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?php echo $this->sName; ?></title>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->appendStylesheet($this->basePath() . '/vendor/bootstrap-responsive.css', 'all')
                    ->appendStylesheet($this->basePath() . '/vendor/bootstrap.css', 'all')
                    ->appendStylesheet($this->basePath() . '/vendor/jquery-ui.min.css', 'all')
                    ->appendStylesheet($this->basePath() . '/vendor/jquery.ui.theme.css', 'all')
                    ->appendStylesheet($this->basePath() . '/css/flightzilla.css', 'all')
                    ->appendStylesheet($this->basePath() . '/css/gantt.css', 'all')
                    ->appendStylesheet($this->basePath() . '/css/silk-sprite.css', 'all');
    ?>

    <style type="text/css">
        body {
            font-size: 13px;

            <?php if ($this->bMinimal !== true):?>
            padding-top: 60px;
            padding-bottom: 40px;
            <?php endif; ?>
        }
    </style>
    <script type="text/javascript">
        var BASE_URL = "<?php echo $this->basePath() ?>",
            BUGZILLA = "<?php echo $this->sBugzilla ?>",
            GO_BUGZILLA = "<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'go-bugzilla')); ?>",
            PRINT = "<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'print')); ?>";
    </script>
    <?php
    echo $this->headScript()->appendFile($this->basePath() . '/vendor/jquery.min.js')
                            ->appendFile($this->basePath() . '/vendor/jquery.ui.custom.min.js')
                            ->appendFile($this->basePath() . '/vendor/bootstrap.min.js')
                            ->appendFile($this->basePath() . '/vendor/jquery.tablesorter.min.js')
                            ->appendFile($this->basePath() . '/js/flightzilla.js');
    ?>
</head>
<body class="<?php if ($this->bMinimal === true):?>minimal<?php endif;?>">
<?php if ($this->bMinimal === true):?>
    <div class="wrapper">
        <?php echo $this->content; ?>
    </div>
<?php else: ?>
    <div class="wrapper <?php echo ($this->sRoute === 'login') ? 'container login' : 'container-fluid'; ?>">
        <?php
            echo $this->content
        ?>

        <hr />
        <footer>
            <p id="footer-left"><?php echo $this->sName; ?>, based on <a href="https://github.com/hpbuniat/flightzilla">flightzilla</a> - <span id="spanYear">&copy; <?php echo date('Y'); ?></span> <a href="mailto:hpbuniat@googlemail.com">Hans-Peter Buniat</a>.</p>
        </footer>
    </div>
    <div class="modal hide fade" id="flightzillaModal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3></h3>
        </div>
        <div class="modal-body">
            <p></p>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Close</a>
        </div>
    </div>
    <p id="loading" class="loading">
        <img src="<?php echo $this->basePath() . '/img/ajax-loader.gif'; ?>" />
    </p>

    <?php echo $this->inlineScript(); ?>
<?php endif; ?>
</body>
</html>
