<?php
    foreach($this->aData as $sDate => $aData) {
        foreach ($aData['base']['campaigns'] as $sCampaign => $aCampaign) {
            if ($aCampaign['visits'] > 100) {
                echo '<table class="bugTable table table-striped table-bordered table-condensed" style="width: 100%; margin-bottom: 10px;">';
                echo $this->partial('analytics/partial/row.phtml', array(
                    'sDate' => $sDate,
                    'sName' => $sCampaign,
                    'aData' => $aCampaign,
                    'aBase' => $aData['base']
                ));

                foreach ($aData['compare'] as $sCompareDate => $aCompare) {
                    foreach ($aCompare['campaigns'] as $sCompareCampaign => $aCompareCampaign) {
                        if ($sCompareCampaign == $sCampaign) {
                            echo $this->partial('analytics/partial/row.phtml', array(
                                'sDate' => $sDate,
                                'sName' => $sCampaign,
                                'aData' => $aCampaign,
                                'sCompareDate' => $sCompareDate,
                                'aCompareData' => $aCompareCampaign,
                                'aBase' => $aData['base'],
                                'bCompare' => true
                            ));
                        }
                    }
                }

                echo '</table>';
            }
        }
    }
?>