<?php
foreach ($this->aTickets as $this->oTicket):
    /* @var $oTicket \Flightzilla\Model\Ticket\Type\Bug */
    ?>
    <blockquote class="bq-small">
        <?php
        $this->oTask = $this->oTicket;
        echo sprintf('<p>%s</p>', $this->render('flightzilla/index/partial/bug-line.phtml'));
        echo $this->render('flightzilla/index/partial/flag.phtml');
        ?>
    </blockquote>
    <?php
endforeach;
?>
<hr />
<p class="clearfix p-small">
    <a href="javascript:window.location.reload()" class="btn btn-primary btn-large refresh-button pull-right">Reload the ticket-list</a>
</p>

