<?php if ($this->bThumbnail !== false): ?>
<a href="#" class="thumbnail droppable" data-drop="assign" data-user="<?php echo $this->oResource->getEmail(); ?>">
    <?php
    echo $this->gravatar($this->oResource->getGravatar(), array(
            'imgSize' => 90,
            'secure' => true
        ),
        array(
            'class' => 'avatar',
            'title' => $this->sMemberName
        ));
    ?>
</a>
<?php
    echo sprintf('<h5><strong>%s</strong></h5>', $this->sMemberName);
else:
    echo sprintf('<h5 class="droppable" data-drop="confirmed" data-user="%s"><i class="icon-user"></i> <strong>%s</strong></h5>', $this->oResource->getEmail(), $this->sMemberName);
endif;


?>
<blockquote>
    <div class="btn-toolbar">
        <div class="btn-group">
            <a href="#" class="btn disabled droppable tooltip" data-title="Drop a pin, to set it to ASSIGNED" data-drop="assign"><i class="icon-wrench"></i></a>
        </div>
        <div class="btn-group">
            <a href="#" class="btn disabled droppable tooltip" data-title="Drop a pin, to set it to CONFIRMED" data-drop="confirmed" data-user="<?php echo $this->oResource->getEmail(); ?>"><i class="icon-pause"></i></a>
        </div>
        <div class="btn-group">
            <a href="#" class="btn disabled droppable tooltip" data-title="Drop a pin, to set it to RESOLVED" data-drop="resolve" data-user="<?php echo $this->oResource->getEmail(); ?>"><i class="icon-ok-circle"></i></a>
        </div>
    </div>
</blockquote>
