<?php
$aProjects = array();
foreach ($this->aProjects as $oProject) {

    /* @var \Flightzilla\Model\Ticket\Type\Project $oProject */
    $fRevenue = $oProject->getRevenue();
    $iComplexity = $oProject->getComplexity();
    $iRisk = $oProject->getRisk();
    $iProbability = $oProject->getRevenueProbability();

    if (empty($fRevenue) !== true or (empty($iComplexity) !== true and empty($iRisk) !== true)) {
        $aProjects[] = array(
            'id' => $oProject->id(),
            'summary' => $oProject->title(),
            'assignee' => $oProject->getAssignee(),
            'depends' => $oProject->getDependentProjects(),
            'revenue' => $fRevenue,
            'complexity' => $iComplexity,
            'risk' => $iRisk,
            'probability' => $iProbability,
            'score-estimation' => $oProject->getRevenueScoreEstimation(),
            'score-real' => $oProject->getRevenueScoreActual(),
            'estimation' => $oProject->getEstimationTimeOfDependencies(),
            'worked' => $oProject->getActualTimeOfDependencies(),
            'left' => $oProject->getLeftTimeOfDependencies(),
            'status' => ((isset($this->aKanban[$oProject->id()]) === true) ? \Flightzilla\Model\Kanban\Status::$aStatusText[$this->aKanban[$oProject->id()]] : '-')
        );
    }
}

echo json_encode($aProjects);
