<div class="row">
    <?php
    echo $this->render('flightzilla/index/partial/overview.phtml');
    ?>

    <div class="col-lg-10">
        <form id="buglist-form" method="get" target="_blank" action="#">
            <?php
            foreach ($this->aProjects as $iTicket => $oProject) {
                /* @var \Flightzilla\Model\Ticket\Type\Bug $oProject */
                try {
                    echo $this->partial('flightzilla/index/partial/table.phtml', array(
                        'captionTicket' => $oProject,
                        'sBugzilla' => $this->layout()->sBugzilla,
                        'bugs' => $oProject->getDependsAsStack(),
                        'ready' => 'REVIEWED'
                    ));
                }
                catch (\Flightzilla\Model\Ticket\Type\Bug\Exception $e) {
                    echo sprintf('<div class="alert alert-danger">An Error occured when fetching the tickets for: %s</div>', $oProject->title());
                }
            }
            ?>
        </form>

    </div>

    <h4 id="quickList" class="bugCount" style="display:none"></h4>
</div>
