<?php echo $this->render('flightzilla/index/partial/header.phtml'); ?>

<div class="row-fluid">
    <?php
    echo $this->partial('flightzilla/project/partial/sidebar.phtml', array(
                                                                          'sHeading' => 'Team',
                                                                          'aStack' => $this->aStack,
                                                                     ));
    ?>

    <div class="span10">
        <form id="buglist-form" method="get" target="_blank" action="<?php echo $this->url('flightzilla', array('controller' => 'index', 'action' => 'go-bugzilla'))?>">
            <?php
            foreach ($this->aResources as $oResource) {
                echo sprintf('<div class="gantt t%s" data-target="%s"></div>', md5($oResource->getName()), $oResource->getName());
            }
            ?>

        </form>

        <script type="text/javascript">
            $(function() {
                $(".gantt").each(function() {
                    var $this = $(this);
                    $this.gantt({
                        source: "planning/data/type/resource/name/" + $this.data('target'),
                        navigate: "scroll",
                        scale: "days",
                        maxScale: "months",
                        minScale: "days",
                        days: ["M", "T", "W", "T", "F", "S", "S"],
                        itemsPerPage: 50
                    });
                });

                $(".gantt").popover({
                    selector: ".bar",
                    title: "I'm a popover",
                    content: "And I'm the content of said popover."
                });
            });
        </script>

    </div>
</div>
