<?php echo $this->render('flightzilla/index/partial/header.phtml'); ?>
<div class="row-fluid">
    <div class="hidden" id="ganttGraph">

    </div>

    <script type="text/javascript">
        $(function() {
            $("#ganttGraph").gantt({
                source: <?php echo $this->sProjects; ?>,
                navigate: "scroll",
                scale: "days",
                maxScale: "weeks",
                minScale: "hours",
                dow: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
                itemsPerPage: 25,
                scrollToToday: true
            });
        });
    </script>

    <div>
        <?php foreach ($this->aErrors as $sError): ?>
        <div class="alert alert-error">
            <button class="close" data-dismiss="alert">×</button>
            <strong>Error!</strong> <?php echo $sError; ?>
        </div>
        <?php endforeach; ?>
    </div>
</div>

<div class="row-fluid">
    <ul class="nav nav-tabs">
        <?php foreach ($this->aProjects as $aProject): ?>
        <li>
            <a href="#project<?php echo $aProject['ticket']; ?>" title="<?php echo $aProject['name']; ?>" data-toggle="tab">
                <?php
                $sString = str_ireplace('thema: ', '', $aProject['name']);
                if (strlen($sString) > 15) {
                    $sString = substr($sString, 0, 12) . '...';
                }

                echo $sString;
                ?>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>

    <div class="tab-content">
        <?php foreach ($this->aProjects as $aProject): ?>
        <div class="tab-pane" id="project<?php echo $aProject['ticket']; ?>">
            <?php foreach ($aProject['tasks'] as $oTask): ?>
            <blockquote>
                <h4>
                    <?php
                        $this->oTask = $oTask;
                        echo $this->render('flightzilla/index/partial/bug-line.phtml');
                    ?>
                    <small><?php echo date('d.m.Y H:i', $oTask->getStartDate()); ?> - <?php echo date('d.m.Y H:i', $oTask->getEndDate()); ?></small>
                </h4>
                <pre><?php echo $oTask->long_desc->thetext; ?></pre>
            </blockquote>
            <?php endforeach; ?>
        </div>
        <?php endforeach; ?>
    </div>
</div>
