<div class="callout callout-info toggle" data-target="diff-graph">
    <h3>Created vs. Resolved Issues (<?php echo sprintf('%d created ~ %d resolved', $this->aDailyDifference['total']['created'], $this->aDailyDifference['total']['resolved']);?>)</h3>
</div>

<div id="project-canvas" class="diff-graph print-fullwidth"></div>

<?php $this->inlineScript()
    ->appendFile($this->basePath() . '/vendor/d3.min.js')
    ->appendFile($this->basePath() . '/js/graph.js');
?>
<script type="text/javascript">
    $(function() {
        // draw
        diffChart.draw(<?php echo json_encode($this->aDailyDifference['daily']); ?>);
    });
</script>


<div class="callout callout-info toggle" data-target="feature-ticket-bars">
    <h3>Feature/Bug-Rates</h3>
</div>

<div class="feature-ticket-bars">
    <?php foreach ($this->aStatsFeatureTickets as $sTime => $aStats): ?>
        <div>
            <span><?php echo $sTime; ?></span>
            <div class="progress progress-striped">
                <?php foreach ($aStats as $sTicketType => $aValues): ?>
                    <div title="<?php echo sprintf('%s: %s%% (%d of %d tickets)', $sTicketType, $aValues['per'], $aValues['num'], $aValues['sum']); ?>" class="tipper progress-bar progress-bar-<?php echo \Flightzilla\Model\Stats\Service::$aTypeColor[$sTicketType]; ?>" style="width: <?php echo $aValues['per']; ?>%"></div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<div class="callout callout-info toggle" data-target="ticket-efficiency-bars">
    <h3>Ticket-Efficiency</h3>
</div>

<div class="ticket-efficiency-bars">
    <?php foreach ($this->aTicketEfficiency as $sTime => $aStats): ?>
        <div>
            <span><?php echo $sTime; ?></span>
            <div class="progress progress-striped">
                <div title="<?php echo sprintf('%s: %s%% (%d of %d hours)', 'Returned', $aStats['returned']['per'], $aStats['returned']['num'], $aStats['returned']['sum']); ?>" class="tipper progress-bar progress-bar-success" style="width: <?php echo $aStats['returned']['per']; ?>%"></div>
                <div title="<?php echo sprintf('%s: %s%% (%d of %d hours)', 'Invested', $aStats['invested']['per'], $aStats['invested']['num'], $aStats['invested']['sum']); ?>" class="tipper progress-bar progress-bar-warning" style="width: <?php echo $aStats['invested']['per']; ?>%"></div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<div class="callout callout-info toggle" data-target="project-times">
    <h3>Project-Times</h3>
</div>

<div class="project-times">
    <ul class="nav nav-tabs" id="myTab">
        <?php foreach ($this->aProjectTimes as $sTime => $aStats): ?>
            <li><a data-toggle="tab" href="#a<?php echo substr(md5($sTime), 0, 6); ?>"><?php echo $sTime; ?></a></li>
        <?php endforeach; ?>
    </ul>

    <div class="tab-content">
        <?php foreach ($this->aProjectTimes as $sTime => $aStats): ?>
            <div class="tab-pane" id="a<?php echo substr(md5($sTime), 0, 6); ?>">
                <?php foreach ($aStats as $iTicket => $aHours):
                    if ($aHours['hoursWindow'] > 0):
                        $fWidth = (100 * round($aHours['hoursWindow'] / $aHours['hours'], 2));
                        ?>
                        <div class="col-lg-4">
                            <span><?php echo (is_numeric($iTicket) === true) ? $this->oTicketService->getBugById($iTicket)->title() : ucwords($iTicket); ?></span>
                        </div>
                        <div class="col-lg-8">
                            <div class="progress progress-striped">
                                <div title="<?php echo sprintf('%s: %d hours', 'Time-Window', $aHours['hoursWindow']); ?>" class="tipper progress-bar progress-bar-success" style="width: <?php echo $fWidth; ?>%"></div>
                                <div title="<?php echo sprintf('%s: %d hours', 'Total', $aHours['hours']); ?>" class="tipper progress-bar progress-bar-warning" style="width: <?php echo 100 - $fWidth; ?>%"></div>
                            </div>
                        </div>
                <?php endif;
                endforeach; ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
