<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">flightzilla</a>
      <div class="nav-collapse pull-right">
          <ul class="nav">
            <li><a href="javascript:window.location.reload()"><i class="icon-refresh icon-white"></i>Refresh</a></li>
            <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'logout'))?>"><i class="icon-off icon-white"></i> Sign Out</a></li>
          </ul>
      </div>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="<?php echo ($this->mode === 'dashboard') ? 'active' : ''; ?>"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'dashboard'))?>">Dashboard</a></li>
          <li class="<?php echo ($this->mode === 'list') ? 'active' : ''; ?>"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'))?>">Bugs</a></li>
          <li class="<?php echo ($this->mode === 'team') ? 'active' : ''; ?>"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'team'))?>">Team</a></li>
          <li class="<?php echo ($this->mode === 'mergy') ? 'active' : ''; ?>"><a href="<?php echo $this->url(array('controller' => 'mergy', 'action' => 'index'))?>">Mergy</a></li>
          <li class="<?php echo ($this->mode === 'sprint') ? 'active' : ''; ?>"><a href="<?php echo $this->url(array('controller' => 'planning', 'action' => 'sprint'))?>">Ressources</a></li>
          <li class="<?php echo ($this->mode === 'projects') ? 'active' : ''; ?>"><a href="<?php echo $this->url(array('controller' => 'planning', 'action' => 'projects'))?>">Projects</a></li>
          <li class="<?php echo ($this->mode === 'summary') ? 'active' : ''; ?>"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'summary'))?>">Summary</a></li>
          <li class="<?php echo ($this->mode === 'analytics') ? 'active' : ''; ?>"><a href="<?php echo $this->url(array('controller' => 'analytics', 'action' => 'index'))?>">Analytics</a></li>
          <li class="divider"></li>
        </ul>
        <form class="navbar-search">
            <input type="text" id="searchId" value="Search" onblur="if (this.value=='') { this.value='Search'; }" onfocus="if (this.value=='Search') { this.value=''; }" class="" />
        </form>
      </div>
    </div>
  </div>
</div>
