<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-20 at 21:10:27.
 */
class Model_Ticket_Source_BugzillaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Model_Ticket_Source_Bugzilla
     */
    protected $_object;

    /**
     *
     */
    protected $_oMock;

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() {
        unset($this->_object, $this->_oMock);

    }

    /**
     * Create the test-object
     */
    public function create($sContent = '') {
        $this->_oMock = $this->getMockBuilder('Zend_Http_Client')->disableOriginalConstructor()->setMethods(
            'request',
            'getBody'
        )->getMock();
        $this->_oMock->expects($this->any())->method('request')->will($this->returnSelf());
        $this->_oMock->expects($this->any())->method('getBody')->will($this->returnValue($sContent));

        Zend_Registry::set('_login', 'test');
        Zend_Registry::set('_password', 'test');

        $this->_object = new Model_Ticket_Source_Bugzilla(true, $this->_oMock);
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::setView
     * @todo   Implement testSetView().
     */
    public function testSetView() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getChuckStatus
     * @todo   Implement testGetChuckStatus().
     */
    public function testGetChuckStatus() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getPriorities
     * @todo   Implement testGetPriorities().
     */
    public function testGetPriorities() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getSeverities
     * @todo   Implement testGetSeverities().
     */
    public function testGetSeverities() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getCount
     * @todo   Implement testGetCount().
     */
    public function testGetCount() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getSummary
     * @todo   Implement testGetSummary().
     */
    public function testGetSummary() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::product
     * @todo   Implement testProduct().
     */
    public function testProduct() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::user
     * @todo   Implement testUser().
     */
    public function testUser() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::updateTicket
     * @todo   Implement testUpdateTicket().
     */
    public function testUpdateTicket() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getBugsChangedToday
     * @todo   Implement testGetBugsChangedToday().
     */
    public function testGetBugsChangedToday() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getBugList
     * @todo   Implement testGetBugList().
     */
    public function testGetBugList() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getAllBugs
     * @todo   Implement testGetAllBugs().
     */
    public function testGetAllBugs() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getOpenBugs
     * @todo   Implement testGetOpenBugs().
     */
    public function testGetOpenBugs() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getFixedBugs
     * @todo   Implement testGetFixedBugs().
     */
    public function testGetFixedBugs() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getReopenedBugs
     * @todo   Implement testGetReopenedBugs().
     */
    public function testGetReopenedBugs() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getUnworkedWithoutOrganization
     * @todo   Implement testGetUnworkedWithoutOrganization().
     */
    public function testGetUnworkedWithoutOrganization() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getWaiting
     * @todo   Implement testGetWaiting().
     */
    public function testGetWaiting() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getInprogress
     * @todo   Implement testGetInprogress().
     */
    public function testGetInprogress() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getOpenConcepts
     * @todo   Implement testGetOpenConcepts().
     */
    public function testGetOpenConcepts() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getBugListByIds
     * @todo   Implement testGetBugListByIds().
     */
    public function testGetBugListByIds() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getFixedBugsInBranch
     * @todo   Implement testGetFixedBugsInBranch().
     */
    public function testGetFixedBugsInBranch() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getFixedBugsInTrunk
     * @todo   Implement testGetFixedBugsInTrunk().
     */
    public function testGetFixedBugsInTrunk() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getFixedBugsUnknown
     * @todo   Implement testGetFixedBugsUnknown().
     */
    public function testGetFixedBugsUnknown() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getBugsWithFlag
     * @todo   Implement testGetBugsWithFlag().
     */
    public function testGetBugsWithFlag() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getFilteredList
     * @todo   Implement testGetFilteredList().
     */
    public function testGetFilteredList() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getThemes
     * @todo   Implement testGetThemes().
     */
    public function testGetThemes() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getThemesAsStack
     * @todo   Implement testGetThemesAsStack().
     */
    public function testGetThemesAsStack() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getUpdateTestserver
     * @todo   Implement testGetUpdateTestserver().
     */
    public function testGetUpdateTestserver() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getTeamBugs
     * @todo   Implement testGetTeamBugs().
     */
    public function testGetTeamBugs() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getMemberBugs
     * @todo   Implement testGetMemberBugs().
     */
    public function testGetMemberBugs() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getUnthemedBugs
     * @todo   Implement testGetUnthemedBugs().
     */
    public function testGetUnthemedBugs() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getThemedOpenBugs
     * @todo   Implement testGetThemedOpenBugs().
     */
    public function testGetThemedOpenBugs() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getBugById
     * @todo   Implement testGetBugById().
     */
    public function testGetBugById() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getTeam
     * @todo   Implement testGetTeam().
     */
    public function testGetTeam() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getFirstWorkedDate
     * @todo   Implement testGetFirstWorkedDate().
     */
    public function testGetFirstWorkedDate() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getStats
     * @todo   Implement testGetStats().
     */
    public function testGetStats() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Model_Ticket_Source_Bugzilla::getStatuses
     * @todo   Implement testGetStatuses().
     */
    public function testGetStatuses() {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
