<!DOCTYPE html>
<html lang="en">
<head>
    <title><?php echo $this->sName; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php $this->headMeta()->prependHttpEquiv('Content-Type', 'text/html; charset=utf-8')?>
    <?php echo $this->headMeta()?>
    <link rel="stylesheet" href="<?php echo $this->baseUrl('min/?g=css'); ?>" type="text/css" media="screen" />
    <style type="text/css">
      body {
        font-size: 13px;
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <script type="text/javascript">
        var BASE_URL = "<?php echo $this->baseUrl('/') ?>",
            BUGZILLA = "<?php echo $this->sBugzilla ?>";
    </script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('min/?g=js'); ?>"></script>
</head>
<body class="<?php $oRequest = Zend_Controller_Front::getInstance()->getRequest(); echo $oRequest->getControllerName() . '_' . $oRequest->getActionName() ?>">
    <div class="<?php echo ($oRequest->getActionName() === 'login' ? 'container' : 'container-fluid'); ?>">
        <?php echo $this->layout()->content ?>

        <hr />
        <footer>
            <p id="footer-left"><?php echo $this->sName; ?>, based on <a href="https://github.com/hpbuniat/flightzilla">flightzilla</a> - <span id="spanYear">&copy; <?php echo date('Y'); ?></span> <a href="mailto:hpbuniat@googlemail.com">Hans-Peter Buniat</a>.</p>
        </footer>
    </div>
    <div class="modal hide" id="flightzillaModal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3></h3>
        </div>
        <div class="modal-body">
            <p></p>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Close</a>
        </div>
    </div>
    <p id="loading" class="loading">
        <img src="<?php echo $this->baseUrl('resource/img/ajax-loader.gif'); ?>" />
    </p>
</body>
</html>
