<?php echo $this->render('index/partial/header.phtml')?>

<div class="row-fluid kanban">
    <div class="span12">
        <div class="row-fluid">
            <div class="span2 border-right">
                <h4>Stack</h4>
                <div class="row-fluid">
                    <div class="span12">
                        <?php
                            $this->aStack = $this->allBugsOpen;
                            echo sprintf('<h5>waiting (%d)</h5>', count($this->aStack));
                            echo $this->render('kanban/partial/column.phtml');
                        ?>
                    </div>
                </div>
            </div>
            <div class="span2 border-right">
                <h4>Concept</h4>
                <div class="row-fluid">
                    <div class="span6">
                        <?php
                            $this->aStack =  $this->allScreenWip;
                            echo sprintf('<h5>wip (%d)</h5>', count($this->aStack));
                            echo $this->render('kanban/partial/column.phtml');
                        ?>
                    </div>
                    <div class="span6">
                        <?php
                            $this->aStack =  $this->allScreenApproved;
                            echo sprintf('<h5>ready (%d)</h5>', count($this->aStack));
                            echo $this->render('kanban/partial/column.phtml');
                        ?>
                    </div>
                </div>
            </div>
            <div class="span5 border-right">
                <h4>Development</h4>
                <div class="row-fluid">
                    <div class="span5">
                        <?php
                            $this->aStack =  $this->openWaiting;
                            echo sprintf('<h5>waiting (%d)</h5>', count($this->aStack));
                            echo $this->render('kanban/partial/column.phtml');
                        ?>
                    </div>
                    <div class="span5">
                        <?php
                            $this->aStack =  $this->bugsWip;
                            echo sprintf('<h5>wip (%d)</h5>', count($this->aStack));
                            echo $this->render('kanban/partial/column.phtml');
                        ?>
                    </div>
                    <div class="span2">
                        <?php
                            $this->aStack =  $this->bugsFixedWithoutTesting;
                            echo sprintf('<h5>ready (%d)</h5>', count($this->aStack));
                            echo $this->render('kanban/partial/column.phtml');
                        ?>
                    </div>
                </div>
            </div>
            <div class="span2 border-right">
                <h4>Testing</h4>
                <div class="row-fluid">
                    <div class="span7">
                        <?php
                            $this->aStack =  $this->allBugsTesting;
                            echo sprintf('<h5>wip (%d)</h5>', count($this->aStack));
                            echo $this->render('kanban/partial/column.phtml');
                        ?>
                    </div>
                    <div class="span5">
                        <?php
                            $this->aStack = $this->bugsBranch;
                            echo sprintf('<h5>ready (%d)</h5>', count($this->aStack));
                            $this->ready  = Model_Ticket_Type_Bug::STATUS_VERIFIED;
                            echo $this->render('kanban/partial/column.phtml');
                        ?>
                    </div>
                </div>
            </div>
            <div class="span1">
                <h4>Staging</h4>
                <div class="row-fluid">
                    <div class="span12">
                        <?php
                            $this->aStack = $this->bugsTrunk;
                            echo sprintf('<h5>Release (%d)</h5>', count($this->aStack));
                            $this->ready  = Model_Ticket_Type_Bug::STATUS_VERIFIED;
                            echo $this->render('kanban/partial/column.phtml');
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    setTimeout("location.reload(true);", 120000);
</script>